services:
- docker
script: 
- make buildproject
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
deploy:
    provider: script
    skip_cleanup: true
    script:
    - make pushimage
